[package]
name = "physics_00"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_rapier2d = { git = "https://github.com/dimforge/bevy_rapier", branch = "master" }
